### ISSUE TITLE
to change the scope of the method getInteger to public

### ISSUE THREAD

**Issue by flambrette** [iryndin/jdbf#31]
I had difficulties reading an Integer field from a file.
I tried with DbdRecord.getString(fieldName) and DbdRecord.getBigDecimal(fieldName) but i received an unexpected result.
So i found a solution with the method toMap(fieldName) but the easiest way seems to use the method getInteger from DbfRecord. Unfortunetly this method is private.

**Comment by iryndin** [comment]
@flambrette could you please make a pull request which makes `getInteger` `public` instead of `private` ?

**Comment by iryndin** [comment]
Closing this issue since PR fixing it is merged now
